export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENT_SUCCESS = 'FETCH_APPOINTMENT_SUCCESS';
export const FETCH_TREATMENTS_SUCCESS = 'FETCH_TREATMENTS_SUCCESS';
export const FETCH_TREATMENT_SUCCESS = 'FETCH_TREATMENT_SUCCESS';
export const FETCH_DOCTORS_SUCCESS = 'FETCH_DOCTORS_SUCCESS';
export const FETCH_DOCTOR_SUCCESS = 'FETCH_DOCTOR_SUCCESS';
